insert into tbl_product(name,category,description,discount,image,price,supplier) values ('Samsung Galaxy Z Flip5',0,'Samsung Galaxy Z Flip 5 được đánh giá cao về thiết kế cho đến cấu hình sản phẩm, điện thoại sẽ ra mắt trong thời gian sắp tới nên là đề tài bàn luận của nhiều fan thương hiệu Samsung. Với những điểm mạnh riêng của điện thoại chắc chắn sẽ không làm người dùng thất vọng khi sử dụng.',0.3,'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/s/a/samsung-galaxy-z-flip-5-256gb_1_4.png',17990000,'Samsung'),
																					     ('Samsung Galaxy S23 Ultra',0,'Samsung S23 Ultra là dòng điện thoại cao cấp của Samsung, sở hữu camera độ phân giải 200MP ấn tượng, chip Snapdragon 8 Gen 2 mạnh mẽ, bộ nhớ RAM 8GB mang lại hiệu suất xử lý vượt trội cùng khung viền vuông vức sang trọng. Sản phẩm được ra mắt từ đầu năm 2023.',0.35,'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/s/a/samsung-galaxy-s23-ultra.png',22490000,'Samsung'),
																						 ('Xiaomi Redmi Note 12',0,'Xiaomi Redmi Note 12 8GB 128GB tỏa sáng với diện mạo viền vuông cực thời thượng cùng hiệu suất mạnh mẽ nhờ sở hữu con chip Snapdragon 685 ấn tượng. Chất lượng hiển thị hình ảnh của Redmi Note 12 Vàng cũng khá sắc nét thông qua tấm nền AMOLED 120Hz hiện đại. Chưa hết, máy còn sở hữu cụm 3 camera với độ rõ nét lên tới 50MP cùng viên pin 5000mAh và s ạc nhanh 33W giúp đáp ứng được mọi nhu cầu sử dụng của người dùn',0.45,'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/g/t/gtt_7766_3__1_5.jpg',8490000,'Xiaomi'),
																						 ('iPhone 13',0,'Về kích thước, iPhone 13 sẽ có 4 phiên bản khác nhau và kích thước không đổi so với series iPhone 12 hiện tại. Nếu iPhone 12 có sự thay đổi trong thiết kế từ góc cạnh bo tròn (Thiết kế được duy trì từ thời iPhone 6 đến iPhone 11 Pro Max) sang thiết kế vuông vắn (đã từng có mặt trên iPhone 4 đến iPhone 5S, SE).',0.25,'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-13_2_.png',23990000,'Apple'),
																						 ('iPhone 14 Pro Max',0,'iPhone 14 Pro Max có sự cải thiện lớn màn hình so với iPhone 13 Pro Max. Sự khác biệt giữ phiên bản iPhone 14 Pro Max 256GB và bản tiêu chuẩn 128GB chỉ là bộ nhớ trong. Dưới đây là một số cải tiến nổi bật trên iPhone 14 Pro Max mà có thể bạn chưa biết!',0.15,'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-14-pro-max-256gb.png',29490000,'Apple'),
																						 ('Apple MacBook Air M1 2020',1,'Macbook Air M1 là dòng sản phẩm có thiết kế mỏng nhẹ, sang trọng và tinh tế cùng với đó là giá thành phải chăng nên MacBook Air đã thu hút được đông đảo người dùng yêu thích và lựa chọn. Đây cũng là một trong những phiên bản Macbook Air mới nhất mà khách hàng không thể bỏ qua khi đến với CellphoneS. Dưới đây là chi tiết về thiết kế, cấu hình của máy.',0.15,'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/a/i/air_m2.png',19490000,'Apple'),
																						 ('Laptop ASUS TUF Gaming F15 FX506HC-HN144W',1,'Laptop Asus TUF Gaming F15 FX506HC-HN144W sở hữu thiết kế táo bạo và độc đáo bậc nhất trên thị trường với gam màu Graphite black nổi bật mà cực huyền bí. Với hiệu năng đỉnh cao và linh kiện cấu thành có chất lượng đứng đầu thị trường, chiếc laptop Asus Gaming này được kỳ vọng dễ dàng chinh phục mọi thử thách và đồng hành với các game thủ trên mọi đấu trường.',0.35,'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/5/h/5h53.png',22490000,'Asus'),
																						 ('Apple MacBook Air M1 2020',1,'Macbook Air M1 là dòng sản phẩm có thiết kế mỏng nhẹ, sang trọng và tinh tế cùng với đó là giá thành phải chăng nên MacBook Air đã thu hút được đông đảo người dùng yêu thích và lựa chọn. Đây cũng là một trong những phiên bản Macbook Air mới nhất mà khách hàng không thể bỏ qua khi đến với CellphoneS. Dưới đây là chi tiết về thiết kế, cấu hình của máy.',0.25,'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/a/i/air_m2.png',19490000,'Apple'),
																						 ('Laptop ASUS ZenBook UM3402YA-KM074W',1,'Laptop Asus Zenbook UM3402YA-KM074W chiếm được khá nhiều tình cảm của người dùng nhờ lối thiết kế cũng như hiệu năng đỉnh cao mà nó mang lại. Để tìm hiểu thêm laptop Asus Zenbook UM3402YA-KM074W có phù hợp với nhu cầu sử dụng của bản thân hay không, hãy tìm hiểu chi tiết ngay sau đây.',0.15,'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/2/_/2.17_1.png',17490000,'Asus'),
																						 ('Laptop Dell Latidude 7320 9PPWV',1,'Laptop Dell Latitude 7320 9PPWV là chiếc laptop được thiết kế chuyên nghiệp để xử lý các tác vụ văn phòng, duyệt web, email,...Màn hình 13.3 inch tiện lợi cho di chuyển, bộ vi xử lý Intel Core i5 siêu mạnh mẽ là những điểm mạnh của chiếc laptop này. Cụ thể hơn hãy xem đoạn mô tả sau đây để nắm được ưu thế khi chọn mua laptop Dell Latitude nhé.',0.1,'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:80/plain/https://cellphones.com.vn/media/catalog/product/l/a/laptop-dell-latitude-7320-9ppwv.png',21490000,'Dell')
																						 
